@hostname = http://localhost
@port = 3000
@url = {{hostname}}:{{port}}

###
GET {{url}}/api/clients

###
GET {{url}}/api/clients/viajes

###
GET {{url}}/api/clients/hotels/4


###
POST {{url}}/api/clients
Content-Type: application/json

{
    "nombre": "Nuevo contacto",
    "apellidos": "Apellidos",
    "direccion": "Calle de prueba 34 ",
    "email": "prueba66@no.com",
    "telefono": "449877765",
    "fecha_nacimiento": "1978-05-01",
    "dni": "1234665RU"
  }


###
PUT {{url}}/api/clients/28
Content-Type: application/json

{
    "nombre": "Contacto Prueba",
    "apellidos": "Apellidos",
    "direccion": "Calle prueba 34 ",
    "email": "prueba24@no.com",
    "telefono": "445775765",
    "fecha_nacimiento": "1980-05-01",
    "dni": "12345guay"
  }

###
DELETE {{url}}/api/clients/28


