@hostname = http://localhost
@port = 3000
@url = {{hostname}}:{{port}}

###
GET {{url}}/api/hotels

###
POST {{url}}/api/hotels
Content-Type: application/json

{
    "nombre": "Hotel Leonardo", 
    "direccion":" Calle Martin Dolmen 58", 
    "ciudad":"Malaga", 
    "estrellas":"3", 
    "descripcion": "Hotel moderno en malaga, cerca de la playa", 
    "tarifa": "200"
}


###
PUT {{url}}/api/hotels/10
Content-Type: application/json

{
    "nombre": "Hotel Leonardo", 
    "direccion":" Calle Martin Dolmen 58", 
    "ciudad":"Malaga", 
    "estrellas":"4", 
    "descripcion": "Hotel moderno en malaga, cerca de la playa", 
    "tarifa": "230"
}


###
DELETE {{url}}/api/hotels/9


